# [[plugins]]
# repo = 'davidhalter/jedi-vim'
# on_ty = ['py']

# Laravel Blade
[[plugins]]
repo = 'jwalton512/vim-blade''
on_ty = ['php.blade']

# markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ty = ['md']

[[plugins]]
repo = 'kannokanno/previm'
on_ty = ['md']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ty = ['md']
