[[plugins]]
repo = 'Shougo/unite.vim'
if = '!has("nvim")'

[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("nvim")'
on_i = 1

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if ='!has("nvim")'
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if ='has("nvim")'
on_i = 1

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ty = ['py']
