[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'zchee/deoplete-jedi'
if = "has('nvim')"
depends = ['Shougo/deoplete.nvim']
on_ft = ['python']
on_i = 1

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']

[[plugins]]
repo = 'thinca/vim-quickrun'
on_ft = ['tex']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
