[[plugins]]
repo = 'Shougo/unite.vim'
if = '!has("nvim")'

[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = '!has("lua")'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ty = ['py']

# markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ty = ['md']

[[plugins]]
repo = 'kannokanno/previm'
on_ty = ['md']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ty = ['md']
