[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/deol.nvim'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'daigo-kimura/annotation-vim'
