<<<<<<< HEAD
=======
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = "!has('nvim')"
on_i = 1

[[plugins]]
repo = 'roxma/nvim-yarp'
if = "!has('nvim')"
on_i = 1

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
>>>>>>> d2438d3... Install vim-fugitive
repo = 'zchee/deoplete-jedi'
on_ft = ['python']

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']

[[plugins]]
repo = 'thinca/vim-quickrun'
on_ft = ['tex']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
